# trigger:
#   branches:
#     include:
#       - feature/**
#       - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.13'


jobs:
  - job: Build
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(pythonVersion)'
        displayName: 'Set up Python: $(pythonVersion)'

      - script: |
          sudo apt-get update
          sudo apt-get upgrade -y
        displayName: 'Update System Packages'

      - task: CopyFiles@2
        displayName: 'Copy Source and Test Directories'
        inputs:
          SourceFolder: '.'
          Contents: |
            src/**
            tests/**
          TargetFolder: '$(Build.SourcesDirectory)'

      - script: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Python Package Dependencies'

      - script: |
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install msodbcsql18 -y
        displayName: 'Install Microsoft ODBC 18'
      
      - script: |
          ip addr show | grep "inet " | awk '{print $2}' | cut -d'/' -f1
        displayName: 'Show IP Woolie Test'
  
      # - script: |
      #     source venv/bin/activate
      #     cd "$(Build.SourcesDirectory)" # Change directory to the copied source
      #     pytest tests/utility/test_utility.py
      #   displayName: 'Run Pytest for utility mainly SQL connection'