version: 1
disable_existing_loggers: False
formatters:
    file_all_output:
        class: utility.logger.BatchJsonRootFormatter
    standard:
        class: utility.logger.JsonStdoutFormatter
        format: '%(asctime)s|%(levelname)s|%(module)s|%(funcName)s|'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    print_stdout:
        level: DEBUG
        formatter: standard
        class: logging.StreamHandler
        stream: 'ext://sys.stdout'
    file_all_output:
        level: DEBUG
        formatter: file_all_output
        filename: 'all_output.json'
        class: logging.FileHandler
        mode: 'a'
    file_monitoring:
        level: INFO
        formatter: file_all_output
        filename: 'monitoring.json'
        class: logging.FileHandler
        mode: 'a'

loggers:
    all_output:
        handlers: [print_stdout, file_all_output]
        level: DEBUG
        propagate: True
    all_output.monitoring:
        handlers: [file_monitoring]
        level: INFO
        propagate: True